services:
  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION:-11.5.5}
    ports:
      - 3000:3000
    volumes:
      - ./dist/grafana-clickhouse-datasource:/var/lib/grafana/plugins/grafana-clickhouse-datasource
      - ./grafana/provisioning:/etc/grafana/provisioning
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/login"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - GF_LOG_LEVEL=debug
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=true
    networks:
      - grafana

  clickhouse-server:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION:-24.7-alpine}
    container_name: clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./data_dir:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host", "clickhouse-server", "--query", "SELECT 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - grafana

  tables-creater:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION:-24.7-alpine}
    container_name: tables-creater
    entrypoint: ["clickhouse-client", "--host", "clickhouse-server", "--queries-file", "/dev/shm/tables.sql"]
    depends_on:
      clickhouse-server:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./clickhouse/tables.sql:/dev/shm/tables.sql
    networks:
      - grafana

  c24-parser:
    image: c24-expences:test
    container_name: c24-parser
    depends_on:
      clickhouse-server:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./input:/input
      - ./config.yaml:/etc/config.yaml
    command: sh -c "exec /usr/local/bin/c24-expences -config /etc/config.yaml"
    networks:
      - grafana

networks:
  grafana: 
