{
 "title": "C24 Expenses",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Income/Expences",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMonth(date) AS month,\n    sumIf(amount, amount < 0) AS expenses,\n    sumIf(amount, amount > 0) AS earnings\nFROM\n    transactions\nWHERE\n    primary_class != 'Savings'\nGROUP BY\n    month\nORDER BY\n    month;"
    }
   ]
  },
  {
   "title": "Primary category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    primary_class,\n    abs(sum(amount)) AS total_expenses\nFROM\n    transactions\nWHERE\n    amount < 0 \n    AND primary_class != 'Savings'\n    AND date >= toDate(parseDateTimeBestEffort('${__from:date}'))\n    AND date <= toDate(parseDateTimeBestEffort('${__to:date}'))\nGROUP BY\n    primary_class\nORDER BY\n    total_expenses DESC;"
    }
   ]
  },
  {
   "title": "Sub category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    secondary_class,\n    abs(sum(amount)) AS total_expenses\nFROM\n    transactions\nWHERE\n    amount < 0 \n    AND secondary_class != 'Saving'\n    AND date >= toDate(parseDateTimeBestEffort('${__from:date}'))\n    AND date <= toDate(parseDateTimeBestEffort('${__to:date}'))\nGROUP BY\n    secondary_class\nORDER BY\n    total_expenses DESC;"
    }
   ]
  },
  {
   "title": "Expenses by primary category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMonth(date) AS time,\n    primary_class,\n    abs(sum(amount)) AS total_expenses\nFROM\n    transactions\nWHERE\n    amount < 0 AND primary_class != 'Savings' AND\n    time >= toDate(parseDateTimeBestEffort('${__from:date}')) AND time <= toDate(parseDateTimeBestEffort('${__to:date}'))\nGROUP BY\n    time, primary_class\nORDER BY\n    time ASC;"
    }
   ]
  }
 ]
}